version: '3.8'

services:
  mysql:
    build: ./docker/mysql
    container_name: sistema-vendas-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-123}
      MYSQL_DATABASE: ${DB_NAME:-BDVENDAS}
      MYSQL_USER: ${DB_USER:-usuario}
      MYSQL_PASSWORD: ${DB_PASSWORD:-123}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-123}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
    driver: local
