# Generated by Django 5.2.7 on 2025-10-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_user_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
