# Generated by Django 5.2.7 on 2025-10-27 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('qtd_estoque', models.IntegerField(verbose_name='Quantidade em Estoque')),
                ('estoque_minimo', models.IntegerField(default=10, verbose_name='Estoque Mínimo')),
                ('fornecedor', models.ForeignKey(db_column='for_id', on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='suppliers.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'tb_produtos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=10, verbose_name='Tipo')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('quantidade_anterior', models.IntegerField(verbose_name='Quantidade Anterior')),
                ('quantidade_atual', models.IntegerField(verbose_name='Quantidade Atual')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='inventory.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'db_table': 'tb_movimentacoes_estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['qtd_estoque'], name='tb_produtos_qtd_est_40a106_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['produto', '-data_movimentacao'], name='tb_moviment_produto_efd282_idx'),
        ),
    ]
